Controllers/AulaController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tcc_Senai.Data;
using Tcc_Senai.Models;

namespace Tcc_Senai.Controllers
{
    public class AulaController : Controller
    {
        private readonly IESContext _context;
        public AulaController(IESContext context)
        {
            this._context = context;
        }

        //GET Index
        public async Task<IActionResult> Index()
        {
            return View(await _context.Aulas.Include(a => a.Turma).Include(u => u.UnidadeCurricular).Include(f => f.Funcionario).OrderBy(a => a.Data).ToListAsync());
        }

        //GET Create
        public ActionResult Create()
        {
            // trazendo as turmas do banco
            var turmas = _context.Turmas.OrderBy(t => t.Sigla).ToList();
            turmas.Insert(0, new Turma() { Id = 0, Sigla = "Selecione a Turma" });
            ViewBag.Turmas = turmas;

            // trazendo as unidades do banco
            var unidades = _context.UnidadeCurriculares.OrderBy(u => u.Nome).ToList();
            unidades.Insert(0, new UnidadeCurricular() { Id = 0, Nome = "Selecione a Unidade Curricular" });
            ViewBag.Unidades = unidades;

            // trazendo os funcionarios do banco
            var funcionarios = _context.Funcionarios.OrderBy(f => f.NomeCompleto).ToList();
            funcionarios.Insert(0, new Funcionario() { Id = 0, NomeCompleto = "Selecione o Funcionário" });
            ViewBag.Funcionarios = funcionarios;
         
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id", "IdTurma", "Data", "HorarioInicio", "HorarioFim", "IdUc", "IdFunc")]Aula aula)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // se o usuário tiver contrato intermitente e
                    // se a data da aula não coincidir com a folga do funcionário, entra no if
                    if (isIntermitente(aula) && dayLimit(aula))
                    {
                        ViewData["MSG_ERR"] = "Erro! A data selecionada coincide com a folga desse Funcionário!";
                    }
                    else
                    {
                        // se não houver aula na data e horário passados, insere a aula no banco
                        if (!haveAulaT(aula, null) && !haveAulaF(aula, null))
                        {
                            // se o funcionario não ultrapassar as 10 horas de trabalho
                            if (calculaHora(aula))
                            {
                                // adicionando a aula ao banco
                                _context.Add(aula);
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                            else
                            {
                                ViewData["MSG_ERR"] = "Erro! O Funcionário já ultrapassou o limite de horas trabalhadas no dia selecionado!";
                            }
                        }
                        else
                        {
                            ViewData["MSG_ERR"] = "Erro! Já existe uma aula com essa turma ou com esse funcionário cadastrada nessa data e coincidente com este horário";
                        }

                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            ViewBag.Turmas = _context.Turmas.OrderBy(t => t.Sigla).ToList();
            ViewBag.Unidades = _context.UnidadeCurriculares.OrderBy(u => u.Nome).ToList();
            ViewBag.Funcionarios = _context.Funcionarios.OrderBy(f => f.NomeCompleto).ToList();
            return View();
        }

        //GET Edit
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null) 
            {
                return NotFound();
            }
            var aula = await _context.Aulas.SingleOrDefaultAsync(a => a.Id == id);
            if (aula == null)
            {
                return NotFound();
            }
            ViewBag.Turmas = _context.Turmas.OrderBy(t => t.Sigla).ToList();
            ViewBag.Unidades = _context.UnidadeCurriculares.OrderBy(u => u.Nome).ToList();
            ViewBag.Funcionarios = _context.Funcionarios.OrderBy(f => f.NomeCompleto).ToList();
            return View(aula);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("Id", "IdTurma", "Data", "HorarioInicio", "HorarioFim", "IdUc", "IdFunc")]Aula aula)
        {
            if (id != aula.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                // se o usuário tiver contrato intermitente e
                // se a data da aula não coincidir com a folga do funcionário, entra no if
                if (isIntermitente(aula) && dayLimit(aula))
                {
                    ViewData["MSG_ERR"] = "Erro! A data selecionada coincide com a folga desse Funcionário!";
                }
                else
                {
                    // se não houver aula no mesmo dia e horário, entra no if
                    if (!haveAulaT(aula, id) && !haveAulaF(aula, id))
                    {
                        // se o professor não ultrapassar o limite de horas trabalhadas por dia, entra no if
                        if (calculaHora(aula))
                        {
                            try
                            {
                                // atualizando o banco
                                _context.Update(aula);
                                await _context.SaveChangesAsync();
                            }
                            catch (DbException)
                            {

                                if (!AulaExists(aula.Id))
                                {
                                    NotFound();
                                    return NotFound();
                                }
                                else
                                {
                                    throw;
                                }
                            }
                            return RedirectToAction(nameof(Index));

                        }
                        else
                        {
                            ViewData["MSG_ERR"] = "Erro! O Funcionário já ultrapassou o limite de horas trabalhadas no dia selecionado!";
                        }
                    }
                    else
                    {
                        ViewData["MSG_ERR"] = "Erro! Já existe uma aula com essa turma ou com esse funcionário cadastrada nessa data e coincidente com este horário";
                    }
                }
               
            }
            ViewBag.Turmas = _context.Turmas.OrderBy(t => t.Sigla).ToList();
            ViewBag.Unidades = _context.UnidadeCurriculares.OrderBy(u => u.Nome).ToList();
            ViewBag.Funcionarios = _context.Funcionarios.OrderBy(f => f.NomeCompleto).ToList();
            return View(aula);
        }

        // GET Delete
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var aula = await _context.Aulas.SingleOrDefaultAsync(a => a.Id == id);
            if (aula == null)
            {
                return NotFound();
            }
            return View(aula);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var aula = await _context.Aulas.SingleOrDefaultAsync(m => m.Id == id);
            _context.Aulas.Remove(aula);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool AulaExists(long? id)
        {
            return _context.Aulas.Any(e => e.Id == id);
        }

        // retorna true se o funcionario tem aula
        private bool haveAulaT(Aula newAula, long? id)
        {
            bool tem = false;
            var aulas = _context.Aulas.Where(a => a.Turma.Id.Equals(newAula.IdTurma) && a.Data.Equals(newAula.Data)).AsNoTracking().ToList();
            if (aulas != null)
            {
                foreach (var aula in aulas)
                {
                    // se os horários da turma se coincidirem, retorna verdadeiro
                    if (aula.HorarioInicio.TimeOfDay <= newAula.HorarioFim.TimeOfDay && aula.HorarioFim.TimeOfDay >= newAula.HorarioInicio.TimeOfDay)
                    {
                        // se id enviado for igual ao id da aula vindo do banco e o tem for false (Usado no editar)
                        if (id == aula.Id && tem == false)
                        {
                            continue;
                        }
                        else
                        {
                            tem = true;
                        }
                    }
                }
            }
            return tem;
        }

        // retorna true se a turma tem aula
        private bool haveAulaF(Aula newAula, long? id)
        {
            bool tem = false;
            var aulas = _context.Aulas.Where(a => a.Funcionario.Id.Equals(newAula.IdFunc) && a.Data.Equals(newAula.Data)).AsNoTracking().ToList();
            
            // Se a consulta do funcionario não estiver nula, entra na condição
            if (aulas != null)
            {
                foreach (var aula in aulas)
                {

Controllers/TurmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tcc_Senai.Data;
using Tcc_Senai.Models;

namespace Tcc_Senai.Controllers
{
    public class TurmaController : Controller
    {
        private readonly IESContext _context;
        public TurmaController(IESContext context)
        {
            this._context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Turmas.Include(i => i.Curso).OrderBy(c => c.Sigla).ToListAsync());
        }
        // GET: Turma Create
        public ActionResult Create()
        {
            var cursos = _context.Cursos.OrderBy(i => i.Nome).ToList();
            cursos.Insert(0, new Curso() { Id = 0, Nome = "Selecione o Curso" });
            ViewBag.Cursos = cursos;

            ViewBag.Semestre = new[]
            {
                new SelectListItem(){ Value = "", Text = "Selecione o Semestre"},
                new SelectListItem(){ Value = "Primeiro", Text = "Primeiro"},
                new SelectListItem(){ Value = "Segundo", Text = "Segundo"}
            };
            return View();
        }
        //POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id", "IdCurso", "Modulo", "Sigla", "Ano", "Semestre")] Turma turma)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(turma);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            var cursos = _context.Cursos.OrderBy(i => i.Nome).ToList();
            cursos.Insert(0, new Curso() { Id = 0, Nome = "Selecione o Curso" });
            ViewBag.Cursos = cursos;

            ViewBag.Semestre = new[]
            {
                new SelectListItem(){ Value = "", Text = "Selecione o Semestre"},
                new SelectListItem(){ Value = "Primeiro", Text = "Primeiro"},
                new SelectListItem(){ Value = "Segundo", Text = "Segundo"}
            };
            return View(turma);
        }
        // GET: Turma/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var turma = await _context.Turmas.SingleOrDefaultAsync(m => m.Id == id);
            if (turma == null)
            {
                return NotFound();
            }
            ViewBag.Cursos = _context.Cursos.OrderBy(b => b.Nome).ToList();

            ViewBag.Semestre = new[]
            {
                new SelectListItem(){ Value = "", Text = "Selecione o Semestre"},
                new SelectListItem(){ Value = "Primeiro", Text = "Primeiro"},
                new SelectListItem(){ Value = "Segundo", Text = "Segundo"}
            };
            return View(turma);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("Id", "IdCurso", "Modulo", "Sigla", "Ano", "Semestre")] Turma turma)
        {
            if (id != turma.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurmaExists(turma.Id))
                    {
                        NotFound();


                        return NotFound();
                    }
                   
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Cursos = _context.Cursos.OrderBy(b => b.Nome).ToList();

            ViewBag.Semestre = new[]
            {
                new SelectListItem(){ Value = "", Text = "Selecione o Semestre"},
                new SelectListItem(){ Value = "Primeiro", Text = "Primeiro"},
                new SelectListItem(){ Value = "Segundo", Text = "Segundo"}
            };
            return View(turma);
        }
        private bool TurmaExists(long? id)
        {
            return _context.Turmas.Any(e => e.Id == id);
        }

        // GET: Turma/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var turma = await _context.Turmas.SingleOrDefaultAsync(m => m.Id == id);
            _context.Cursos.Where(i => turma.IdCurso ==
            i.Id).Load();
            if (turma == null)
            {
                return NotFound();
            }
            return View(turma);
        }
        // POST: Turma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var turma = await _context.Turmas.SingleOrDefaultAsync(m => m.Id == id);
            _context.Turmas.Remove(turma);
            TempData["Message"] = "Turma " + turma.Sigla.ToUpper() + " foi removido";
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET List
        public async Task<IActionResult> List(long? id)
        {
            // trazendo do banco todas as turmas do curso selecionado na view List de Curso
            return View(await _context.Turmas.Include(i => i.Curso).Where(t => t.IdCurso.Equals(id)).OrderBy(c => c.Sigla).ToListAsync());
        }

        // GET Cronograma
        public IActionResult Cronograma(long? id)
        {
            // trazendo do banco todas as aulas da turma selecionada
            var aulas = _context.Aulas.Include(a => a.Turma).Include(u => u.UnidadeCurricular).Include(f => f.Funcionario).Where(c => c.IdTurma.Equals(id)).OrderBy(a => a.Data).ToList();
            var turma = _context.Turmas.SingleOrDefault(t => t.Id.Equals(id));
            ViewBag.Sigla = turma.Sigla;
            return View(aulas);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tcc_Senai</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tcc_Senai</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tcc_Senai - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutSenai.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/css/responsivo/assets/icomoon/styles.css" />
    <link rel="stylesheet" href="~/css/responsivo/css/datatables.css" />
    <link rel="stylesheet" href="~/css/responsivo/bootstrap.css" />
    <link rel="stylesheet" href="~/css/responsivo/bootstrap_limitless.css" />
    <link rel="stylesheet" href="~/css/responsivo/layout.css" />
    <link rel="stylesheet" href="~/css/responsivo/components.css" />
    <link rel="stylesheet" href="~/css/responsivo/colors.css" />
    <link rel="stylesheet" href="~/css/responsivo/css/all.css" />
    <link rel="stylesheet" href="~/css/Layout/Home.css" />
    <link rel="stylesheet" href="~/css/Layout/Geral.css" />
    @RenderSection("Contents", required: false)

</head>
<body class="">
    <!-- Main navbar -->
    <div id="carregando" style="display: none;">
        <div id="carregando-fundo"></div>
        <div id="carregando-img">
            <i class="icon-spinner2 spinner mr-2"></i>
            <p><strong>Aguarde...</strong></p>
        </div>
    </div>


    <div class="page-header page-header-light bg-info-700">

        <div class="page-header-content header-elements-md-inline header-flex">
            <div class="page-title d-flex">
                <a href="@Url.Action("Index", "Home")" class="d-inline-block">
                    <img src="~/Images/Responsivo/sistema-fiep-logo.png" height="80" width="210">
                </a>
            </div>
            <div class="title-senai">
                <h6 class="ml-5 p-2 font-weight-semibold"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">SENAI CRONOGRAMAS</font></font></h6>
            </div>

            <div class="nav-item dropdown dropdown-user margin">

                <div class="ml-4  media-title font-weight-semibold">Senai Portão</div>
                <div class=" ml-4 font-size-xs opacity-50">
                    <i class="icon-pin font-size-sm"></i> &nbsp;Curitiba-PR
                </div>
            </div>

            <div class="menu-mobile-header">
                <a class="icon close-menu" href="#">
                    <i class="icon-paragraph-justify3"></i>
                </a>
                <div class="menu-links">
                    <a id="cadastros" class="mobile-item" href="#"><i class="fas fa-arrow-down"></i> CADASTROS</a>
                    <div id="sub-cad" class="submenu">
                        <a href="@Url.Action("Index","Modalidade")" class="mobile-sub-item"><i class="fas fa-paperclip"></i> MODALIDADE </a>
                        <a href="@Url.Action("Index","UnidadeCurricular")" class="mobile-sub-item"><i class="icon-book mr-2"></i> UNIDADE CURRICULAR </a>
                        <a href="@Url.Action("Index","Curso")" class="mobile-sub-item"><i class="fas fa-graduation-cap"></i> CURSO </a>
                        <a href="@Url.Action("Index","Funcionario")" class="mobile-sub-item"><i class="fas fa-chalkboard-teacher"></i> FUNCIONARIO </a>
                        <a href="@Url.Action("Index","Turma")" class="mobile-sub-item"><i class="fas fa-user-graduate"></i> TURMA </a>
                        <a href="@Url.Action("Index","Aula")" class="mobile-sub-item"><i class="fas fa-book-reader"></i> AULA </a>
                        @*<a href="@Url.Action("Index","Semestre")" class="mobile-item">SEMESTRE </a>*@
                        @*<a href="@Url.Action("Index","GerarCurso")" class="mobile-item">GERAR CURSOS </a>
                    <a href="@Url.Action("Index", "Coordenador")" class="mobile-item">COORDENADOR </a>*@
                    </div>

                    <a id="cronogramas" class="mobile-item" href="#"><i class="fas fa-arrow-down"></i> CRONOGRAMA</a>
                    <div id="sub-cro" class="submenu">
                        <a href="@Url.Action("List", "Funcionario")" class="mobile-sub-item"><i class="fas fa-chalkboard-teacher"></i> FUNCIONÁRIO</a>
                        <a href="@Url.Action("List", "Curso")" class="mobile-sub-item"><i class="fas fa-user-graduate"></i> TURMA</a>
                        <a href="@Url.Action("List", "UnidadeCurricular")" class="mobile-sub-item"><i class="icon-book mr-2"></i> UNIDADE CURRICULAR</a>
                    </div>
                </div>
            </div>


            <div class="user-icon-section">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown dropdown-user ">
                        <a href="#" class="breadcrumb-elements-item dropdown-toggle mr-5 margin-icon" data-toggle="dropdown" aria-expanded="false">
                            <img src="~/Images/Responsivo/user.png" class="rounded-circle mr-2 " height="35" width="35" alt="" />
                            <font style="vertical-align: inherit;">
                                CONECTADO
                            </font>
                            <span>@User.Identity.Name</span>
                        </a>
                    </li>
                </ul>
            </div>

            <!-- <div class="dropdown-menu dropdown-menu-right bg-info-700">


        <a href="@Url.Action("MeuPerfil","Principal")" class="dropdown-item "><i class="icon-user"></i> MEU PERFIL </a>


        <a href="@Url.Action("Acesso","Register")" class="dropdown-item "><i class="icon-user-plus"></i> NOVO USUÁRIO </a>



        <a href="@Url.Action("Login","Acesso")" class="dropdown-item"><i class="icon-exit"></i> SAIR </a>

        <div class="dropdown-divider mb-2 bg-white"></div>
    </div> -->

        </div>
    </div>


    <div class="navbar navbar-expand-md navbar-light  bg-info-700">
        <div class="text-center d-md-none w-100">
            <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-navigation">
                <i class="icon-unfold mr-2"></i>
                Navigation
            </button>
        </div>




        <div class="navbar-collapse collapse " id="navbar-navigation ">
            <ul class="navbar-nav ">


                <li class="nav-item">
                    <a class="navbar">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="navbar">
                    </a>
                </li>


                <li class="nav-item dropdown">
                    <a href="#" class="p-2 breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-list"></i>
                            <font style="vertical-align: inherit;">
                                CADASTROS
                            </font>
                    </a>
                    <div class="dropdown-menu  list bg-info-700 ">
                        <a href="@Url.Action("Index","Modalidade")" class="dropdown-item dropdown"><i class="fas fa-paperclip"></i>MODALIDADE </a>
                        <a href="@Url.Action("Index","UnidadeCurricular")" class="dropdown-item dropdown"><i class="icon-book mr-2"></i>UNIDADE CURRICULAR </a>
                        <a href="@Url.Action("Index","Curso")" class="dropdown-item dropdown"><i class="fas fa-graduation-cap"></i>CURSO </a>
                        <a href="@Url.Action("Index","Funcionario")" class="dropdown-item dropdown"><i class="fas fa-chalkboard-teacher"></i>FUNCIONÁRIO </a>
                        <a href="@Url.Action("Index","Turma")" class="dropdown-item dropdown"><i class="fas fa-user-graduate"></i>TURMA </a>
                        <a href="@Url.Action("Index","Aula")" class="dropdown-item dropdown"><i class="fas fa-book-reader"></i>AULA </a>
                        @*<a href="@Url.Action("Index","Semestre")" class="dropdown-item dropdown"><i class=""></i>SEMESTRE </a>*@
                        @*<a href="@Url.Action("Index","GerarCurso")" class="dropdown-item dropdown"><i class=""></i>GERAR CURSOS </a>
        <a href="@Url.Action("Index","Coordenador")" class="dropdown-item dropdown"><i class=""></i>COORDENADOR </a>*@

                        <div class="dropdown-divider mb-2 bg-white"></div>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="navbar">
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a href="#" class="p-2 breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="text-white icon-calendar2 icon mr-2"></i><font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                               GERAR CRONOGRAMAS
                            </font>
                        </font>
                    </a>
                    <div class="dropdown-menu bg-info-700 ">

                        <div class="dropdown-submenu  bg-info-700">
                            <a href="@Url.Action("List", "Funcionario")" class="dropdown-item dropdown"><i class="fas fa-chalkboard-teacher"></i> FUNCIONÁRIO</a>
                            <a href="@Url.Action("List", "Curso")" class="dropdown-item dropdown"><i class="fas fa-user-graduate"></i> TURMA</a>
                            <a href="@Url.Action("List", "UnidadeCurricular")" class="dropdown-item dropdown"><i class="icon-book mr-2"></i> UNIDADE CURRICULAR</a>
                        </div>

                    </div>

                </li>
            </ul>

        </div>
    </div>



   



    <div class="content-wrapper">


        <div class="content">
            @RenderBody()
        </div>
        <div class="navbar navbar-expand-lg navbar-light bg-info-700">
            <div class="text-center d-lg-none w-100">
                <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
                    <i class="icon-unfold mr-2"></i>
                    Rodapé
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-footer">
                <span class="navbar-nav ml-lg-auto">
                    © 2020 SENAI PORTÃO
                </span>
                &nbsp;
                &nbsp;
                &nbsp;

                <ul class="navbar-nav ml-lg-auto">
                </ul>

            </div>
        </div>
    </div>


    <script src="~/js/responsivo/jquery.min.js"></script>
    <script src="~/js/responsivo/bootstrap.bundle.min.js"></script>
    <script src="~/js/responsivo/plugins/blockui.min.js"></script>
    <script src="~/js/responsivo/app.js"></script>
    <script src="~/js/responsivo/Principal.js"></script>
    <script src="~/js/Layout/Geral.js"></script>
    @RenderSection("Styles", required: false)

    @RenderSection("ScriptPage", required: false)

</body>
</html>